# Airtube constant
API_BASE_URL = 'https://data.sensor.community/airrohr/v1/filter/country=BG,NL.json'
# Request constant
USER_AGENT = {'User-Agent': 'Mozilla/5.0'}

SOFIA_MAPPER_ID_STREET = {3633: 'bul."Louis Pasteur"',
                          788: 'ul. "Kozloduy"',
                          3096: 'ploshtad "Pirdop"',
                          29197: 'bul."Cherni vrah"',
                          11124: 'ul. "Lajos Kossuth"',
                          11682: 'ul. "Akad. Petar Dinekov"',
                          3428: 'ul. "Tsaritsa"',
                          4617: 'ul. "Knyaginya Tamara"',
                          5662: 'ul. "Asenova krepost"',
                          5691: 'ul. "Postoyanstvo"',
                          5777: 'ul. "Samokov"',
                          6030: 'ж.к. Христо Смирненски',
                          23176: 'улица „Димитър Яблански“',
                          6134: 'ul. "Maestro Mihail Milkov"',
                          6349: 'ж.к. Дружба',
                          6782: 'ul. "Yastrebets"',
                          7170: 'ul. "Akad. Vera Mutafieva"',
                          7335: 'ж.к. Младост 4',
                          9260: 'g.k. Lyulin 2',
                          9489: 'J.K. Vrabnitsa 1',
                          9676: 'ul. "Vasil Stefanov"',
                          9689: 'ul. "Krayrechna"',
                          9721: 'ul. "Sveti Kipriyan"',
                          10462: 'ul. "Jerusalem"',
                          8543: 'ж.к. Младост 1',
                          10652: 'ul. "18-ta"',
                          10840: 'ul. "Timok"',
                          10946: 'улица „Андрей Сахаров“',
                          10988: 'ul. "Vecherna Prohlada"',
                          11077: 'ж.к. Младост 4',
                          11099: 'bul."Andrey Lyapchev"',
                          11338: 'g.k. Ovcha kupel 1',
                          72308: 'ж.к. Младост 3',
                          6528: 'bul."Tsar Boris III"',
                          11808: 'ж.к. Младост 3',
                          10006: 'ul. "Vasil Radoslavov"',
                          11692: 'ul. "Dimcho Debelyanov"',
                          4466: 'ul. "General Stefan Toshev"',
                          11878: 'ul. "Institutska"',
                          33155: 'ul. "Tsanko Tserkovski"',
                          11971: 'ul. "Bulair"',
                          7836: 'ul. "Louis Eyer"',
                          12219: 'ul. "Akademik Stefan Mladenov"',
                          12793: 'ul. "660-ta"',
                          12475: 'ul. "Velyo Topalovski"',
                          12626: 'ul. "Slatinska"',
                          12775: 'ul. "406-ta"',
                          12785: 'ul. "Rozhdestvo"',
                          13026: 'ul. "Rozova dolina"',
                          13029: 'ul. "Kanala"',
                          13033: 'ul. "Petko Staynov"',
                          13040: 'ul. "Parizhka Komuna"',
                          13209: 'ul. "Vishneva"',
                          6128: 'ul. "Evlia Chelebi"',
                          14067: 'alley"Aleya 6"',
                          14393: 'ul. "Spatnik"',
                          46562: 'ul. "Lyuben Karavelov"',
                          15050: 'ul. "General Mihail Savov"',
                          15056: 'ul. "Hubcha"',
                          15477: 'ж.к. Илинден',
                          8280: 'ul. "Badnina"',
                          16451: 'ul. "Kozloduy"',
                          16793: 'g.k. Dianabad',
                          2889: 'ul. "Sava Mihaylov"',
                          18789: 'ul. "Ana Ahmatova"',
                          44204: 'bul."Yanko Sakazov"',
                          'BG0052A': 'bul."Krastyu Pastuhov"',
                          'BG0040A': 'ul. "Republika"',
                          'BG0050A': 'zh.k. Hipodruma',
                          'BG0073A': 'bul."Tsar Boris III"',
                          'BG0070A': 'Unnamed Road',
                          'BG00001': 'Aleksandar Malinov bul.',
                          19758: 'ul. "Ivan Susanin"',
                          20009: 'ul. "General Kutuzov"',
                          20027: 'ul. "Nikolay Rakitin"',
                          20037: 'bul."Cherni vrah"',
                          20077: 'bul."Vladimir Vazov"',
                          20105: 'ul. Vishovgrad',
                          20110: 'ul. "Voynyagovo"',
                          20119: 'ul. "Podpolkovnik Kalitin"',
                          20612: 'ul. "Beethoven L. V."',
                          20620: 'ul. "Georgi Drazhev"',
                          20622: 'ul. "Samokov"',
                          20911: 'ul. "Otets Paisiy"',
                          21011: 'ж.к. Люлин 10',
                          77041: 'ul. "Despot Slav"',
                          22255: 'ul. "Gechkenli"',
                          22257: 'ul. "Hristo Halachev"',
                          9460: 'ul. "Byal nartsis"',
                          22647: 'ul. "Valcho Georgiev"',
                          22651: 'ж.к. Дружба',
                          2039: 'ul. "Tsar Ivan Asen II"',
                          22930: 'ul. "Boyanski vodopad"',
                          22935: 'Княгиня Мария Луиза',
                          22938: 'ul. "Ekzarh Stefan"',
                          23658: 'ul. Atanas Dukov',
                          6425: 'ж.к. Младост 3',
                          24273: 'bul. "Professor Tsvetan Lazarov"',
                          24278: 'ul. "20-ti april"',
                          12077: 'ul. "Dragoman"',
                          3831: 'zh.k. Manastirski livadi B',
                          7586: 'Васка Баларева',
                          24584: 'ul. "Zhelezopatna"',
                          24679: 'ж.к. Лагера',
                          24874: 'улица св.Киприян',
                          10002: 'bul."Tsar Boris III"',
                          27060: 'ul. "Kristal"',
                          27210: 'ul. "Kapitan Dimitar Spisarevski"',
                          5298: 'ul. "Evlia Chelebi"',
                          28626: 'ul. "Doctor Lyuben Rusev"',
                          49393: 'улица „Къпинка“',
                          29984: 'ul. "Tsar Ivan Shishman"',
                          30927: 'ploshtad "Pope John Paul II"',
                          29788: 'ul. "Professor Ivan Duychev"',
                          31633: 'bul."Yanko Sakazov"',
                          76409: 'ul. "Ivan Susanin"',
                          21092: 'ul. "Haydushka Gora"',
                          32826: 'ul. "Ivan Susanin"',
                          33191: 'ж.к. Дървеница',
                          33406: 'ul. "Buzludzha"',
                          33776: 'ul. "Stara Planina"',
                          33953: 'ul. "Bogdanci"',
                          8049: 'ul. "Buenos Aires"',
                          34742: 'ul. "Kadin vrah"',
                          35250: 'ul. "Trakia"',
                          35676: 'Жилищен комплекс Гоце Делчев',
                          35778: 'ul. "Orel"',
                          35816: 'ж.к. Абдовица',
                          35892: 'ul. "Kestenova gora"',
                          35989: 'g.k. Krasno selo',
                          36192: 'ul. "Lyaskovets"',
                          36475: 'ж.к. Младост 4',
                          36573: 'ul. "744-ta"',
                          36391: 'ul. "Plachkovski Manastir"',
                          36646: 'ul. "Krastyo Sarafov"',
                          36723: 'ul. "Boycho Ognyanov"',
                          36860: 'g.k. Zona B-5',
                          36932: 'ж.к. Младост 1',
                          36935: 'ul. "Kamchia"',
                          37590: 'ul. "Akademik Ilia Petrov"',
                          37931: 'ul. "Profesor Aleksandar Raychev"',
                          38285: 'bul."Dragan Tsankov"',
                          38400: 'ul. "Nikolay Liliev"',
                          6693: 'ж.к. Младост 4',
                          9277: 'ul. "Inzhener Borislav Ogoyski"',
                          6464: 'g.k. Krasna polyana 2',
                          6423: 'ul. "Ruzha"',
                          8075: 'ul. "593-ta"',
                          1103: 'ul. Metodi Andonov',
                          28911: 'ul. "Okolovrasten pat"',
                          10075: 'булевард „Цар Борис Трети“',
                          9229: 'ul. "Kumata"',
                          20298: 'ж.к. Овча купел 1',
                          6096: 'ul. "Zaychar"',
                          36188: 'ul. "Stefan Karadzha"',
                          6851: 'ul. "Georges Danton"',
                          28864: 'улица св.Киприян',
                          'AT22229237': 'ul. "Mimi Balkanska"',
                          'AT22229294': 'bul. "Tsarigradsko shose"',
                          'AT22229335': 'ul. "Boyanski vodopad"',
                          'AT22229350': 'ul. "Professor Arhitekt Petar A. Tashev"',
                          'AT22229455': 'bul. "James Bourchier"',
                          'AT22229480': 'zh.k. Hipodruma',
                          'AT22229482': 'ul. "Akademik Stefan Mladenov"',
                          'AT22229494': 'ul. "Osvobozhdenie"',
                          'AT22229497': 'ul. "Kiril Drangov"',
                          'AT22229503': 'bul. „President Lincoln“',
                          'AT22512471': 'bul."Evlogi i Hristo Georgiev"',
                          'AT22525603': 'bul."Tsar Boris III"',
                          'AT22527228': 'ul. "Kiril Parlichev"',
                          'AT22528883': 'bul."Krastyu Pastuhov"',
                          'AT22532689': 'bul."Knyaginya Maria Luiza"',
                          'AT22535384': 'ul. "Sava Tsonev"',
                          'AT22539001': 'ul. "Nartsis"',
                          9774: 'ul. "Golo Bardo"',
                          11415: 'g.k. Lyulin 5',
                          7182: 'ж.к. Надежда 1',
                          5808: 'ul. "Burel"',
                          6389: 'bul."Sveti Kliment Ohridski"',
                          10688: 'ul. "Pierce Omahony"',
                          35880: 'ul. "Charles Darwin"',
                          6132: 'g.k. Krasna polyana 2',
                          5913: 'ul. "Simeonov vek"',
                          6938: 'ul. "Drushlyavitsa"',
                          8483: 'ul. "Sveti Osij Kordobski"',
                          6090: 'bul."Cherni vrah"',
                          31807: 'g.k. Slavia',
                          35842: 'ul. "Zornitsa"',
                          29335: 'g.k. Peyo K. Yavorov',
                          7918: 'ul. "Prof. Aleksandar Tanev"',
                          35710: 'ul. "Despot Slav"',
                          6680: 'ul. "Sveti Pimen Zografski"',
                          7834: 'ul. "Dragovitsa"',
                          6426: 'ul. "Kozyak"',
                          6224: 'ul. "Rusalka"',
                          6833: 'ul. Metodi Andonov',
                          9462: 'ul. "Lunna Paprat"',
                          6435: 'g.k. Krasna polyana 2',
                          740: 'Shipka Str',
                          21879: 'ж.к. Гевгелийски',
                          1021: 'ul. "Kumata"',
                          6433: 'bul. „President Lincoln“',
                          6150: 'ul. "Lyubata"',
                          5296: 'ul. "Zname na truda"',
                          1472: 'ul. "Professor Kiril Popov"',
                          6345: 'ul. "Vetrushka"',
                          38558: 'ul. "Angel Bukureshtliev"',
                          5380: 'ul. "Doctor Stefan Sarafov"',
                          38282: 'ul. "Radichevtsi"',
                          10706: 'bul. "Simeonovsko Shose',
                          41688: 'ul. "Beethoven L. V."',
                          39789: 'ul. "Krushova Gradina"',
                          11347: 'g.k. Lyulin 8',
                          39245: 'ul. "Yantra"',
                          69916: 'ul. "Simeonovo"',
                          40205: 'ul. Metodi Andonov',
                          40135: 'ul. "Nikola Gabrovski"',
                          38088: 'Unnamed Road',
                          40708: 'ul. "Aleko Konstantinov"',
                          2036: 'ul. "Professor Georgi Bradistilov"',
                          41062: 'ul. "Krum Kyulyavkov"',
                          61292: 'ul. Metodi Andonov',
                          41234: 'bul."Mihai Eminescu"',
                          41626: 'zh.k. Hipodruma',
                          42006: 'ж.к. Зона Б-18',
                          42247: 'ul. "Todor G. Vlaykov"',
                          42864: 'ul. "Montevideo"',
                          42945: 'ul. "Neycho Popov"',
                          43017: 'ж.к. Младост 2',
                          43233: 'ul. "Bosilek"',
                          43553: 'ul. "Trayan Tanev"',
                          43711: 'ul. "Slatinska"',
                          11333: 'ul. "Kostenski vodopad"',
                          44567: 'ul. "Krivina"',
                          23164: 'ul. Akademik Metodi Popov',
                          47028: 'ul. "Matey Preobrazhenski"',
                          47762: 'ul. "Neofit Rilski"',
                          30451: 'ul. "Krushova Gradina"',
                          8077: 'ul. "Radetski"',
                          51083: 'ul. "Vasil Drumev"',
                          30935: 'ul. "Trichkova mogila"',
                          51470: 'bul."Doctor Peter Dertliev"',
                          3178: 'ul. "Tintyava"',
                          52922: 'ul. "Pirotska"',
                          52957: 'bul."Evlogi i Hristo Georgiev"',
                          53041: 'ul. "Belovodski pat"',
                          69524: 'g.k. Krasna polyana 3',
                          53929: 'g.k. Gotse Delchev',
                          61345: 'bul."Tsar Boris III"',
                          54616: 'ul. "Elijah Dimushev"',
                          55238: 'ul. "Zlatna iabalka"',
                          55383: 'ul. "Dimitar Sasalov"',
                          55615: 'ul. "Dobrotitsa Despot"',
                          55691: 'ul. "646-ta"',
                          56052: 'ж.к. Младост 1А',
                          19546: 'ul. "Vranya"',
                          56831: 'ul. "Nezabravka"',
                          57985: 'ul. "Krichim"',
                          67498: 'улица "Вейниче"',
                          58668: 'g.k. Druzhba',
                          58783: 'булевард „Ген. Скобелев“',
                          58801: 'ul. "Todor G. Vlaykov"',
                          58879: 'bul. „Aleksandar S. Pushkin“',
                          59009: 'ul. "Sasho Nikolov-Sladura"',
                          59092: 'ul. "Odesa"',
                          59263: 'ul. "Zhelezopatna"',
                          59280: 'bul."Lomsko Shose"',
                          61128: 'ul. "Dobrovolets"',
                          59709: 'ul. "Ekaterina Bozhilova"',
                          62204: 'ul. "Ohrid"',
                          62697: 'bul."Vitosha"',
                          64668: 'ul. "Kalach"',
                          65637: 'ul. "Sveti Gorazd"',
                          77699: 'ul. Atanas Dukov',
                          65832: 'ul. "Angel Karaliychev"',
                          66570: 'ul. „Georgi S. Rakovski“',
                          66752: 'ul. "Planinitsa"',
                          66853: 'ul. "Arhitekt Georgi Nenov"',
                          66953: 'bul.Kniaz Aleksandar Dondukov',
                          66956: 'ul. "Georgi Rusev"',
                          67693: 'ul. "Professor Benyo Tsonev"',
                          67734: 'ul. "Knyaz Boris I"',
                          55568: 'g.k. Mladost 1',
                          68397: 'g.k. Buxton',
                          68665: 'ul. Metodi Andonov',
                          66625: 'ul. "412-ta"',
                          69176: 'ж.к. Стрелбище',
                          69369: 'Aleksandar Malinov bul.',
                          70127: 'bul."Makedonia"',
                          70453: 'g.k. Druzhba',
                          43934: 'bul."Slivnitsa"',
                          71570: 'ul. "Kaliakra"',
                          71679: 'ul. "Planinets"',
                          62938: 'g.k. Druzhba',
                          72714: 'ul. "Obelya"',
                          74286: 'ul. "Ivan Susanin"',
                          75720: 'bul. "Simeonovsko Shose',
                          76436: 'ul. Akademik Yordan Trifonov',
                          76670: 'ul. "Leonardo Da Vinci"',
                          76707: 'g.k. Levski G',
                          77288: 'bul."Evlogi i Hristo Georgiev"',
                          77427: 'ж.к. Младост 2',
                          77507: 'ul. "165-ta"',
                          77568: 'булевард „Генерал Николай Г. Столетов“',
                          77723: 'ul. "Obikolna"',
                          12400: 'ul. "Zhitnitsa"',
                          77832: 'bul."Louis Pasteur"',
                          787: 'ul. "Kozloduy"',
                          3095: 'ploshtad "Pirdop"',
                          29196: 'bul."Cherni vrah"',
                          11123: 'ul. "Lajos Kossuth"',
                          11681: 'ul. "Akad. Petar Dinekov"',
                          3427: 'ul. "Tsaritsa"',
                          4616: 'ul. "Knyaginya Tamara"',
                          5690: 'ul. "Postoyanstvo"',
                          5776: 'ul. "Samokov"',
                          6029: 'ж.к. Христо Смирненски',
                          23175: 'улица „Димитър Яблански“',
                          6133: 'ul. "Maestro Mihail Milkov"',
                          6348: 'ж.к. Дружба',
                          6781: 'ul. "Yastrebets"',
                          7169: 'ul. "Akad. Vera Mutafieva"',
                          7334: 'ж.к. Младост 4',
                          9675: 'ul. "Vasil Stefanov"',
                          9720: 'ul. "Sveti Kipriyan"',
                          10461: 'ul. "Jerusalem"',
                          8542: 'ж.к. Младост 1',
                          10651: 'ul. "18-ta"',
                          10839: 'ul. "Timok"',
                          10945: 'улица „Андрей Сахаров“',
                          10987: 'ul. "Vecherna Prohlada"',
                          11076: 'ж.к. Младост 4',
                          11098: 'bul."Andrey Lyapchev"',
                          72307: 'ж.к. Младост 3',
                          6527: 'bul."Tsar Boris III"',
                          11807: 'ж.к. Младост 3',
                          10005: 'ul. "Vasil Radoslavov"',
                          11691: 'ul. "Dimcho Debelyanov"',
                          11877: 'ul. "Institutska"',
                          33154: 'ul. "Tsanko Tserkovski"',
                          11970: 'ul. "Bulair"',
                          7835: 'ul. "Louis Eyer"',
                          12218: 'ul. "Akademik Stefan Mladenov"',
                          12792: 'ul. "660-ta"',
                          12474: 'ul. "Velyo Topalovski"',
                          12625: 'ul. "Slatinska"',
                          12774: 'ul. "406-ta"',
                          12784: 'ul. "Rozhdestvo"',
                          13028: 'ul. "Kanala"',
                          13032: 'ul. "Petko Staynov"',
                          13208: 'ul. "Vishneva"',
                          6127: 'ul. "Evlia Chelebi"',
                          14066: 'alley"Aleya 6"',
                          14392: 'ul. "Spatnik"',
                          46561: 'ul. "Lyuben Karavelov"',
                          15049: 'ul. "General Mihail Savov"',
                          15055: 'ul. "Hubcha"',
                          15476: 'ж.к. Илинден',
                          8279: 'ul. "Badnina"',
                          16450: 'ul. "Kozloduy"',
                          16792: 'g.k. Dianabad',
                          2888: 'ul. "Sava Mihaylov"',
                          20008: 'ul. "General Kutuzov"',
                          20026: 'ul. "Nikolay Rakitin"',
                          20036: 'bul."Cherni vrah"',
                          20076: 'bul."Vladimir Vazov"',
                          20104: 'ul. Vishovgrad',
                          20118: 'ul. "Podpolkovnik Kalitin"',
                          20611: 'ul. "Beethoven L. V."',
                          20619: 'ul. "Georgi Drazhev"',
                          20621: 'ul. "Samokov"',
                          20910: 'ul. "Otets Paisiy"',
                          21010: 'ж.к. Люлин 10',
                          77040: 'ul. "Despot Slav"',
                          22254: 'ul. "Gechkenli"',
                          22256: 'ul. "Hristo Halachev"',
                          9459: 'ul. "Byal nartsis"',
                          22646: 'ul. "Valcho Georgiev"',
                          22650: 'ж.к. Дружба',
                          22929: 'ul. "Boyanski vodopad"',
                          22937: 'ul. "Ekzarh Stefan"',
                          6424: 'ж.к. Младост 3',
                          24277: 'ul. "20-ti april"',
                          12076: 'ul. "Dragoman"',
                          24583: 'ul. "Zhelezopatna"',
                          24873: 'улица св.Киприян',
                          10001: 'bul."Tsar Boris III"',
                          27059: 'ul. "Kristal"',
                          27209: 'ul. "Kapitan Dimitar Spisarevski"',
                          5297: 'ul. "Evlia Chelebi"',
                          28625: 'ul. "Doctor Lyuben Rusev"',
                          49392: 'улица „Къпинка“',
                          30926: 'ploshtad "Pope John Paul II"',
                          31632: 'bul."Yanko Sakazov"',
                          21091: 'ul. "Haydushka Gora"',
                          33190: 'ж.к. Дървеница',
                          33405: 'ul. "Buzludzha"',
                          33952: 'ul. "Bogdanci"',
                          8048: 'ul. "Buenos Aires"',
                          34741: 'ul. "Kadin vrah"',
                          35249: 'ul. "Trakia"',
                          35675: 'Жилищен комплекс Гоце Делчев',
                          35777: 'ul. "Orel"',
                          35815: 'ж.к. Абдовица',
                          35891: 'ul. "Kestenova gora"',
                          35990: 'g.k. Krasno selo',
                          36645: 'ul. "Krastyo Sarafov"',
                          36859: 'g.k. Zona B-5',
                          36931: 'ж.к. Младост 1',
                          38399: 'ul. "Nikolay Liliev"',
                          9276: 'ul. "Inzhener Borislav Ogoyski"',
                          6463: 'g.k. Krasna polyana 2',
                          6422: 'ul. "Ruzha"',
                          8074: 'ul. "593-ta"',
                          1102: 'ul. Metodi Andonov',
                          10074: 'булевард „Цар Борис Трети“',
                          6095: 'ul. "Zaychar"',
                          36187: 'ul. "Stefan Karadzha"',
                          6850: 'ul. "Georges Danton"',
                          9773: 'ul. "Golo Bardo"',
                          11414: 'g.k. Lyulin 5',
                          7181: 'ж.к. Надежда 1',
                          5807: 'ul. "Burel"',
                          6388: 'bul."Sveti Kliment Ohridski"',
                          10687: 'ul. "Pierce Omahony"',
                          35879: 'ul. "Charles Darwin"',
                          6131: 'g.k. Krasna polyana 2',
                          5912: 'ul. "Simeonov vek"',
                          6937: 'ul. "Drushlyavitsa"',
                          8482: 'ul. "Sveti Osij Kordobski"',
                          6089: 'bul."Cherni vrah"',
                          31806: 'g.k. Slavia',
                          35841: 'ul. "Zornitsa"',
                          29334: 'g.k. Peyo K. Yavorov',
                          7917: 'ul. "Prof. Aleksandar Tanev"',
                          35709: 'ul. "Despot Slav"',
                          6679: 'ul. "Sveti Pimen Zografski"',
                          7833: 'ul. "Dragovitsa"',
                          6223: 'ul. "Rusalka"',
                          6832: 'ul. Metodi Andonov',
                          9461: 'ul. "Lunna Paprat"',
                          6434: 'g.k. Krasna polyana 2',
                          739: 'Shipka Str',
                          21878: 'ж.к. Гевгелийски',
                          1020: 'ul. "Kumata"',
                          6432: 'bul. „President Lincoln“',
                          6149: 'ul. "Lyubata"',
                          5295: 'ul. "Zname na truda"',
                          1471: 'ul. "Professor Kiril Popov"',
                          6344: 'ul. "Vetrushka"',
                          38557: 'ul. "Angel Bukureshtliev"',
                          5379: 'ul. "Doctor Stefan Sarafov"',
                          38283: 'ul. "Radichevtsi"',
                          10705: 'bul. "Simeonovsko Shose',
                          41687: 'ul. "Beethoven L. V."',
                          39788: 'ul. "Krushova Gradina"',
                          11346: 'g.k. Lyulin 8',
                          39244: 'ul. "Yantra"',
                          40012: 'ul. "Simeonovo"',
                          40204: 'ul. Metodi Andonov',
                          40134: 'ul. "Nikola Gabrovski"',
                          38087: 'Unnamed Road',
                          40707: 'ul. "Aleko Konstantinov"',
                          2035: 'ul. "Professor Georgi Bradistilov"',
                          41061: 'ul. "Krum Kyulyavkov"',
                          61291: 'ul. Metodi Andonov',
                          41233: 'bul."Mihai Eminescu"',
                          41625: 'zh.k. Hipodruma',
                          42246: 'ul. "Todor G. Vlaykov"',
                          42944: 'ul. "Neycho Popov"',
                          43016: 'ж.к. Младост 2',
                          43232: 'ul. "Bosilek"',
                          43552: 'ul. "Trayan Tanev"',
                          43710: 'ul. "Slatinska"',
                          11332: 'ul. "Kostenski vodopad"',
                          44566: 'ul. "Krivina"',
                          23163: 'ul. Akademik Metodi Popov',
                          47027: 'ul. "Matey Preobrazhenski"',
                          30450: 'ul. "Krushova Gradina"',
                          8076: 'ul. "Radetski"',
                          51082: 'ul. "Vasil Drumev"',
                          30934: 'ul. "Trichkova mogila"',
                          51469: 'bul."Doctor Peter Dertliev"',
                          3177: 'ul. "Tintyava"',
                          53040: 'ul. "Belovodski pat"',
                          69523: 'g.k. Krasna polyana 3',
                          61344: 'bul."Tsar Boris III"',
                          54615: 'ul. "Elijah Dimushev"',
                          55382: 'ul. "Dimitar Sasalov"',
                          55690: 'ul. "646-ta"',
                          56051: 'ж.к. Младост 1А',
                          19545: 'ul. "Vranya"',
                          58782: 'булевард „Ген. Скобелев“',
                          58800: 'ul. "Todor G. Vlaykov"',
                          58878: 'bul. „Aleksandar S. Pushkin“',
                          59008: 'ul. "Sasho Nikolov-Sladura"',
                          59091: 'ul. "Odesa"',
                          59708: 'ul. "Ekaterina Bozhilova"',
                          62696: 'bul."Vitosha"',
                          64667: 'ul. "Kalach"',
                          77700: 'ul. Atanas Dukov',
                          65831: 'ul. "Angel Karaliychev"',
                          66569: 'ul. „Georgi S. Rakovski“',
                          66751: 'ul. "Planinitsa"',
                          66852: 'ul. "Arhitekt Georgi Nenov"',
                          66955: 'ul. "Georgi Rusev"',
                          67692: 'ul. "Professor Benyo Tsonev"',
                          67733: 'ul. "Knyaz Boris I"',
                          55567: 'g.k. Mladost 1',
                          68396: 'g.k. Buxton',
                          68664: 'ul. Metodi Andonov',
                          66624: 'ul. "412-ta"',
                          69175: 'ж.к. Стрелбище',
                          70126: 'bul."Makedonia"',
                          70452: 'g.k. Druzhba',
                          43933: 'bul."Slivnitsa"',
                          62937: 'g.k. Druzhba',
                          72713: 'ul. "Obelya"',
                          74284: 'ul. "Ivan Susanin"',
                          76435: 'ul. Akademik Yordan Trifonov',
                          76669: 'ul. "Leonardo Da Vinci"',
                          77287: 'bul."Evlogi i Hristo Georgiev"',
                          77426: 'ж.к. Младост 2',
                          77567: 'булевард „Генерал Николай Г. Столетов“',
                          77722: 'ul. "Obikolna"',
                          12399: 'ul. "Zhitnitsa"',
                          39301: 'ж.к. Младост 4',
                          6196: 'ul. "406-ta"',
                          3968: 'ul. "Badnina"',
                          40013: 'ul. "Simeonovo"',
                          39300: 'ж.к. Младост 4',
                          6195: 'ul. "406-ta"',
                          3967: 'ul. "Badnina"',
                          69917: 'ul. "Simeonovo"'
                          }

PLOVDIV_MAPPER_ID_STREET = {}

CITY_MAPPER = {'Sofia': SOFIA_MAPPER_ID_STREET, 'Plovdiv': 'PLOVDIV_MAPPER_ID_STREET'}
